@startuml List-Four

class People{
    name: String
    age: int

    void toPresent()
}

class Car{
    mark: String
    model: String
    year: int

    void displayInformation()
}

class Product{
    name: String
    price: float
    amount: int

    void totalCalcValue()
}

class Book {
    title: String
    author: String
    numberOfPages: int

    void summary()
}

class Student{
    name: String
    score1: float
    score2: float

    void media()
    void aprovado()
}

@enduml
