@startuml List-Four

class People{
    name: String
    age: int

    void toPresent()
}

class Car{
    mark: String
    model: String
    year: int

    void displayInformation()
}

class Product{
    name: String
    price: float
    amount: int

    void totalCalcValue()
}


@enduml
